# ----------------------------------------------------- 
# Window rules
# ----------------------------------------------------- 

windowrule = tile on, match:class ^(Microsoft-edge)$
windowrule = tile on, match:class ^(Brave-browser)$
windowrule = tile on, match:class ^(Chromium)$
windowrule = float on, match:class ^(pavucontrol)$
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(nm-connection-editor)$
windowrule = float on, match:class ^(qalculate-gtk)$
windowrule = float on, match:class (timeshift-gtk)
windowrule = float on, match:class (main.py)
windowrule = tile on, match:title  ^(chiaki-ng)$
windowrule = float on, move ((monitor_w*1)-window_w-16) ((monitor_h*1)-window_h-44), pin on, match:class (Mullvad VPN)


windowrule = float on, move ((monitor_w*1)-window_w-16) ((monitor_h*1)-window_h-44), pin on, size 400 400, match:class (com.ml4w.calendar)



# Browser Picture in Picture
windowrule = float on, pin on, move 69.5% 4%, match:title ^(Picture-in-Picture)$
#windowrulev2 = pin on, match:title ^(Picture-in-Picture)$
#windowrulev2 = move 69.5% 4%, title:^(Picture-in-Picture)$
