# ----------------------------------------------------- 
# Monitor Setup
# name: "Double écran"
#
# ----------------------------------------------------- 

monitor=DP-2,highrr, 0x0,1
monitor=DP-1,highrr,1920x0,1.25,vrr,2

#hl.monitor({ output = "DP-1", mode = "highrr", position = "1920x0", vrr = 1, scale = 1.25 })
#hl.monitor({ output = "DP-2", mode = "highrr", position = "0x0", scale = 1 })
